### ISSUE TITLE
Formatting of Training Data Files: keys, alis, feat

### ISSUE THREAD

**Issue by mschonwe** [amaas/stanford-ctc#2]
Could you include an example_training_data folder that has an example of the key input files?:
keyfile (keysN.txt)
alisfile (alisN.txt)
datafile (featsN.bin)

It isn't immediately clear what the format of these files should be.  In particular it would be helpful to know the internal layout of the fields within keyfile and alisfile.  One or two 'dummy' examples would save a lot of backtracking from the code.

**Comment by zxie** [comment]
Just sent you a link to some sample files.

**Comment by WesleyZhang1991** [comment]
In the latest README, I could get "keys19.txt" and "alis19.txt". Could you give me an example of "feats*.bin" ?for example "feats19.bin". Thanks!
