### ISSUE TITLE
ImportError: No module named fastdecode

### ISSUE THREAD

**Issue by mschonwe** [amaas/stanford-ctc#4]
decoder_utils.py references fastdecode -- 
    from fastdecode import decode_lm_wrapper

But we're getting:
 "ImportError: No module named fastdecode"

Is there a fastdecode.py module that didn't make it into the repository?

**Comment by zxie** [comment]
Think you can just comment it out; fastdecode is actually a Boost.Python module that's no longer used https://github.com/amaas/stanford-ctc/tree/master/ctc_fast/decoder/fastdecode

**Comment by mschonwe** [comment]
We were able to get past it with:
import ctypes
fastdecode = ctypes.cdll.LoadLibrary('/u2/bin/stanford-ctc/ctc_fast/decoder/fastdecode/fastdecode.so')

Thanks for the tip!  We'll comment it out.
